name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # або ваша гілка

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Next.js for static export
        run: npm run build && npm run export

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5 # Цей крок
        with:
          build_dir: "./out" # Статичні файли після експорту
